### DISCUSSION TITLE
I'm getting SIP data into the homer server.  Now what?

### DISCUSSION THREAD

**Discussion by ChicagoJay** [sipcapture/homer#491] [Q&A] [answered]
I am seeing my SIP traffic in the homer search, but I have no idea how to make useful charts with it.  I see how to add charts to the Dashboard, but I have no idea how to find what I want to see.  In this case, I'd like to see an histogram of simultaneous SIP sessions.   Is that even possible to generate when just receiving raw SIP traffic? 

Are there sample charts somewhere that I am just missing?

Thanks again for the help!

**Comment by adubovikov** [comment]
you can push all stats to influxdb or to prometheus and use Grafana or Grafana's plugin inside of Homer
Also another way is to use charts in Ag-grid

![homer-7-10-2 (1)](https://user-images.githubusercontent.com/4513061/133286009-b6c51c22-7d56-40e5-9ea1-59917d933291.png)

**Reply by ChicagoJay** [reply]
Thanks for this, but my homer looks a little different.  I don't have that chart button, the settings button isn't in my header, and my search button is different.  What am I missing?
    
![image](https://user-images.githubusercontent.com/13546758/133785269-f319c7c2-d428-4bd2-b198-f7a0c9791bca.png)

Thanks!

- J.

**Comment by lmangani** [comment, marked as answer]
Hi @ChicagoJay you need to pull the latest containers to get updated versions of the software (applies to all elements of the stack)
This being said, all of our charting is done from Grafana nowadays, and embedded into the HOMER UI through integration.

**Reply by ChicagoJay** [reply]
So, if I am not using docker, will apt update get them?

**Reply by adubovikov** [reply]
if you have added our repository - yes.

**Reply by ChicagoJay** [reply]
OK - that got it.  Now I have new things to play with!

**Reply by ChicagoJay** [reply]
A howto for linking homer to Grafana (for people who aren't DBAs or programmers) would be REALLY cool!

**Reply by adubovikov** [reply]
first you have to install grafana and do you use prometheus or influxdb as statistics collector ?

**Reply by ChicagoJay** [reply]
I did set up a grafana account.  Do I have to actually install something on the homer server?  I'm not sure which db is in use - it was whatever the default one is.

It looks like I may be running both:

```
homer:~$ sudo ps aux | grep influx
influxdb   547  0.2  2.5 1526348 208828 ?      Sl   08:27   0:16 /usr/bin/influxd -config /etc/influxdb/influxdb.conf
homer:~$ sudo ps aux | grep prom
root       514  1.0  1.3 1058104 108204 ?      Ssl  08:27   0:58 /usr/local/bin/prometheus --config.file=/usr/local/bin/prometheus.yml
```

Is there a way to tell definitively?

**Reply by adubovikov** [reply]
what did you configure in your heplify-server ?

I think the best way to use start using prometheus.

https://github.com/sipcapture/heplify-server/blob/master/example/homer7_config/heplify-server.toml#L13-L15

and it should be like this:
PromAddr        = "0.0.0.0:8899"
PromTargetIP    = "10.1.2.111,10.1.2.4,10.1.2.5,10.1.2.6,10.12.44.222"
PromTargetName  = "sbc_access,sbc_core,kamailio,asterisk,pstn_gateway"

**Reply by ChicagoJay** [reply]
OK, that's odd.  I have 

```
PromAddr              = "0.0.0.0:9096"
PromTargetIP          = "10.31.0.1"
PromTargetName        = "AdminVG"
```
That IP is the core router that is sending data to the heplify server, and the name is my CUBE router.  Also, my Prom port is different.  Maybe you have found the root cause of why my stuff isn't working!

Is the port supposed to be 8899 or 9096?  Is the PromTargetIP supposed to be where the SIP packets are streaming in?  What is PromTargetName supposed to be?

Here is my complete config:
```
HEPAddr               = "0.0.0.0:9060"
HEPTCPAddr            = ""
HEPTLSAddr            = "0.0.0.0:9060"
HEPWSAddr             = "0.0.0.0:3000"
ESAddr                = ""
ESDiscovery           = true
LokiURL               = ""
LokiBulk              = 200
LokiTimer             = 4
LokiBuffer            = 100000
LokiHEPFilter         = [1,5,100]
ForceHEPPayload       = []
PromAddr              = "0.0.0.0:9096"
PromTargetIP          = "10.31.0.1"
PromTargetName        = "AdminVG"
DBShema               = "homer7"
DBDriver              = "postgres"
DBAddr                = "localhost:5432"
DBUser          = "homer_user"
DBPass          = "***"
DBDataTable           = "homer_data"
DBConfTable           = "homer_config"
DBBulk                = 200
DBTimer               = 4
DBBuffer              = 400000
DBWorker              = 8
DBRotate              = true
DBPartLog             = "2h"
DBPartSip             = "1h"
DBPartQos             = "6h"
DBDropDays            = 14
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0
DBDropOnStart         = false
DBUsageProtection     = true
DBUsageScheme         = "percentage"
DBPercentageUsage     = "80%"
DBMaxSize             = "30MB"
Dedup                 = false
DiscardMethod         = []
AlegIDs               = []
CustomHeader          = []
SIPHeader             = []
LogDbg                = ""
LogLvl                = "info"
LogStd                = false
LogSys                = false
Config                = "./heplify-server.toml"
ConfigHTTPAddr        = ""

# Examples:
# -------------------------------------
# ESAddr          = "http://127.0.0.1:9200"
# DBShema         = "homer7"
# DBDriver        = "postgres"
# LokiURL         = "http://localhost:3100/api/prom/push"
# LokiHEPFilter   = [1,5,100]
# PromAddr        = "0.0.0.0:8899"
# PromTargetIP    = "10.1.2.111,10.1.2.4,10.1.2.5,10.1.2.6,10.12.44.222"
# PromTargetName  = "sbc_access,sbc_core,kamailio,asterisk,pstn_gateway"
```
Please tell me if I have anything else messed up in there.

Thanks!

**Reply by adubovikov** [reply]
did you create a job on your prometheus server to get data from heplify ?

https://prometheus.io/docs/prometheus/latest/querying/api/

in two words it should get data from your HEPLIFY_IP:9096 each 5 seconds

here is the example of docker-prometheus

https://github.com/sipcapture/heplify-server/blob/master/docker/hep-prom-graf/prometheus/prometheus.yml#L26-L29

and this you can add to your prometheus.yaml

```
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'heplify-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['heplify-server:9096']
      - 
```

**Reply by ChicagoJay** [reply]
I integrated your suggestions, and here is my /usr/local/bin/prometheus.yml:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'heplify-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['heplify-server:9096']

remote_write:
  - url: "https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push"
    basic_auth:
      username: "*redacted*"
      password: "*redacted*"

```
Not sure what to do next.
