### ISSUE TITLE
No data in homer web

### ISSUE THREAD

**Issue by oussamahammami** [sipcapture/homer#235]
Hi,

I hope this is a configuration issue.
I've tried twice to get homer running, First manually and then using the bash script in a fresh EC2 instance (Centos 7) dedicated for Homer and I have the same issue, there is no data in the web interface. 

I see the the incoming traffic to the homer port 9060 from my kamailio:

```
`U 172.31.XX.XX:5060 -> 172.31.YY.YY9060
....?...O..j....REGISTER sip:XXX.XXX.XXX.XXX SIP/2.0.
Via: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport;branch=z9hG4bKPji7RZWIR0s2dKtOtf-Q6V7xn6WE8NfTfd.
Max-Forwards: 70.
From: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>;tag=plMUUXS1fxVRCa51mZu22C5qt2Hw5GBe.
To: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>.
Call-ID: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH.
CSeq: 54027 REGISTER.
User-Agent: Telephone 1.2.6.
Contact: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX:62141;ob>.
Expires: 300.
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS.
Content-Length:  0.
.


U 172.31.XX.XX:5060 -> 172.31.YY.YY:9060
......?.....O..jSIP/2.0 401 Unauthorized.
Via: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport=16366;branch=z9hG4bKPji7RZWIR0s2dKtOtf-Q6V7xn6WE8NfTfd;received=XXX.XXX.XXX.XXX.
From: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>;tag=plMUUXS1fxVRCa51mZu22C5qt2Hw5GBe.
To: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>;tag=7f832b20adefb68b76c91fba5a3fbcd1.f296.
Call-ID: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH.
CSeq: 54027 REGISTER.
WWW-Authenticate: Digest realm="XXX.XXX.XXX.XXX", nonce="WUPDGllDwe7gv38A7bM5B8ezAKVfTgjf".
Server: kamailio (4.0.7 (x86_64/linux)).
Content-Length: 0.
.


U 172.31.XX.XX:5060 -> 172.31.YY.YY:9060
....?...O..j....REGISTER sip:XXX.XXX.XXX.XXX SIP/2.0.
Via: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport;branch=z9hG4bKPjrlm7Zg-YsJX9Kz-mk9JWWqjBSpQpWszE.
Max-Forwards: 70.
From: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>;tag=plMUUXS1fxVRCa51mZu22C5qt2Hw5GBe.
To: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>.
Call-ID: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH.
CSeq: 54028 REGISTER.
User-Agent: Telephone 1.2.6.
Contact: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX:62141;ob>.
Expires: 300.
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS.
Authorization: Digest username="SIPACCOUNT", realm="XXX.XXX.XXX.XXX", nonce="WUPDGllDwe7gv38A7bM5B8ezAKVfTgjf", uri="sip:XXX.XXX.XXX.XXX", response="e928e4ef3f1b9206c39308a5eb264cac".
Content-Length:  0.
.


U 172.31.XX.XX:5060 -> 172.31.YY.YY:9060
......?.....O..jSIP/2.0 200 OK.
Via: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport=16366;branch=z9hG4bKPjrlm7Zg-YsJX9Kz-mk9JWWqjBSpQpWszE;received=XXX.XXX.XXX.XXX.
From: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>;tag=plMUUXS1fxVRCa51mZu22C5qt2Hw5GBe.
To: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX>;tag=7f832b20adefb68b76c91fba5a3fbcd1.ce88.
Call-ID: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH.
CSeq: 54028 REGISTER.
Contact: <sip:SIPACCOUNT@XXX.XXX.XXX.XXX:62141;ob>;expires=300;received="sip:XXX.XXX.XXX.XXX:16366".
Server: kamailio (4.0.7 (x86_64/linux)).
Content-Length: 0.`

```

I've checked also the database to verify the sipcapture and mysql modules (kamailio):

```
`mysql> select TABLE_SCHEMA, TABLE_NAME,TABLE_ROWS from TABLES where TABLE_SCHEMA like 'homer_data';
+--------------+-----------------------------------+------------+
| TABLE_SCHEMA | TABLE_NAME                        | TABLE_ROWS |
+--------------+-----------------------------------+------------+
| homer_data   | isup_capture_all_20170616         |          0 |
| homer_data   | isup_capture_all_20170617         |          0 |
| homer_data   | isup_capture_all_20170618         |          0 |
| homer_data   | logs_capture                      |          0 |
| homer_data   | report_capture                    |          0 |
| homer_data   | rtcp_capture                      |          0 |
| homer_data   | rtcp_capture_all_20170216         |          0 |
| homer_data   | sip_capture_call_20170616         |         21 |
| homer_data   | sip_capture_call_20170617         |          0 |
| homer_data   | sip_capture_call_20170618         |          0 |
| homer_data   | sip_capture_registration_20170616 |         52 |
| homer_data   | sip_capture_registration_20170617 |          0 |
| homer_data   | sip_capture_registration_20170618 |          0 |
| homer_data   | sip_capture_rest_20170616         |          0 |
| homer_data   | sip_capture_rest_20170617         |          0 |
| homer_data   | sip_capture_rest_20170618         |          0 |
| homer_data   | webrtc_capture                    |          0 |
| homer_data   | webrtc_capture_all_20170616       |          0 |
| homer_data   | webrtc_capture_all_20170617       |          0 |
| homer_data   | webrtc_capture_all_20170618       |          0 |
+--------------+-----------------------------------+------------+
20 rows in set (0.00 sec)

mysql> select * from homer_data.sip_capture_registration_20170616 limit 2\G
*************************** 1. row ***************************
              id: 1
            date: 2017-06-16 10:50:55
        micro_ts: 1497610255042384
          method: REGISTER
    reply_reason:
            ruri: sip:ZZZ.ZZZ.ZZZ.ZZZ
       ruri_user:
     ruri_domain: ZZZ.ZZZ.ZZZ.ZZZ
       from_user: SIPACCOUNT
     from_domain: ZZZ.ZZZ.ZZZ.ZZZ
        from_tag: c7L3evyLasD7jat6uv2l9bVDvFBotSAN
         to_user: SIPACCOUNT
       to_domain: ZZZ.ZZZ.ZZZ.ZZZ
          to_tag:
        pid_user:
    contact_user: SIPACCOUNT
       auth_user:
          callid: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH
     callid_aleg:
           via_1: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport;branch=z9hG4bKPjd8Vuu.hrz.Lb.rmx6M1HkQm3cZGuFCJ8
    via_1_branch: z9hG4bKPjd8Vuu.hrz.Lb.rmx6M1HkQm3cZGuFCJ8
            cseq: 54007 REGISTER
       diversion:
          reason:
    content_type:
            auth:
      user_agent: Telephone 1.2.6
       source_ip: YYY.YYY.YYY.YYY
     source_port: 16366
  destination_ip: 172.31.XX.XX
destination_port: 5060
      contact_ip: XXX.XXX.XXX.XXX
    contact_port: 62141
   originator_ip:
 originator_port: 0
         expires: -1
  correlation_id: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH
   custom_field1:
   custom_field2:
   custom_field3:
           proto: 1
          family: 2
        rtp_stat:
            type: 1
            node: homer01
             msg: REGISTER sip:ZZZ.ZZZ.ZZZ.ZZZ SIP/2.0
Via: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport;branch=z9hG4bKPjd8Vuu.hrz.Lb.rmx6M1HkQm3cZGuFCJ8
Max-Forwards: 70
From: "SIPACCOUNT" <sip:SIPACCOUNT@ZZZ.ZZZ.ZZZ.ZZZ>;tag=c7L3evyLasD7jat6uv2l9bVDvFBotSAN
To: "SIPACCOUNT" <sip:SIPACCOUNT@ZZZ.ZZZ.ZZZ.ZZZ>
Call-ID: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH
CSeq: 54007 REGISTER
User-Agent: Telephone 1.2.6
Contact: "SIPACCOUNT" <sip:SIPACCOUNT@XXX.XXX.XXX.XXX:62141;ob>
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0


*************************** 2. row ***************************
              id: 2
            date: 2017-06-16 10:50:55
        micro_ts: 1497610255040762
          method: 401
    reply_reason: Unauthorized
            ruri:
       ruri_user:
     ruri_domain:
       from_user: SIPACCOUNT
     from_domain: ZZZ.ZZZ.ZZZ.ZZZ
        from_tag: c7L3evyLasD7jat6uv2l9bVDvFBotSAN
         to_user: SIPACCOUNT
       to_domain: ZZZ.ZZZ.ZZZ.ZZZ
          to_tag: 7f832b20adefb68b76c91fba5a3fbcd1.5bae
        pid_user:
    contact_user:
       auth_user:
          callid: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH
     callid_aleg:
           via_1: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport=16366;branch=z9hG4bKPjd8Vuu.hrz.Lb.rmx6M1HkQm3cZGuFCJ8;received=YYY.YYY.YYY.YYY
    via_1_branch: z9hG4bKPjd8Vuu.hrz.Lb.rmx6M1HkQm3cZGuFCJ8
            cseq: 54007 REGISTER
       diversion:
          reason:
    content_type:
            auth:
      user_agent:
       source_ip: 172.31.XX.XX
     source_port: 5060
  destination_ip: YYY.YYY.YYY.YYY
destination_port: 16366
      contact_ip:
    contact_port: 0
   originator_ip:
 originator_port: 0
         expires: -1
  correlation_id: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH
   custom_field1:
   custom_field2:
   custom_field3:
           proto: 1
          family: 2
        rtp_stat:
            type: 2
            node: homer01
             msg: SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP XXX.XXX.XXX.XXX:62141;rport=16366;branch=z9hG4bKPjd8Vuu.hrz.Lb.rmx6M1HkQm3cZGuFCJ8;received=YYY.YYY.YYY.YYY
From: "SIPACCOUNT" <sip:SIPACCOUNT@ZZZ.ZZZ.ZZZ.ZZZ>;tag=c7L3evyLasD7jat6uv2l9bVDvFBotSAN
To: "SIPACCOUNT" <sip:SIPACCOUNT@ZZZ.ZZZ.ZZZ.ZZZ>;tag=7f832b20adefb68b76c91fba5a3fbcd1.5bae
Call-ID: 2OzCf7unuNrFyEk5G4sfj9ZJXyeCQCWH
CSeq: 54007 REGISTER
WWW-Authenticate: Digest realm="ZZZ.ZZZ.ZZZ.ZZZ", nonce="WUO4YFlDtzQYRwYGmM7w/smBopGgMiAX"
Server: kamailio (4.0.7 (x86_64/linux))
Content-Length: 0


2 rows in set (0.00 sec)`

```
Any advice would be great, thanks for any help.
